### ISSUE TITLE
avian3d examples crash when pressing cmd+q due to dev-dependencies disabling default features

### ISSUE THREAD

**Issue by mgi388** [avianphysics/avian#399]
Run an example like this:

```
RUST_BACKTRACE=1 MTL_HUD_ENABLED=1 cargo run --example cubes
```

Press `cmd+q`. See the stack trace:

```
2024-07-06T05:23:01.045525Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-07-06T05:23:01.130152Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
thread 'main' panicked at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/system/system_param.rs:629:17:
Resource requested by (bevy_ecs::event::EventWriter<bevy_window::event::WindowResized>, bevy_ecs::event::EventWriter<bevy_window::event::WindowBackendScaleFactorChanged>, bevy_ecs::event::EventWriter<bevy_window::event::WindowScaleFactorChanged>, bevy_ecs::system::system_param::NonSend<bevy_winit::winit_windows::WinitWindows>, bevy_ecs::system::query::Query<(&mut bevy_window::window::Window, &mut bevy_winit::system::CachedWindow)>, bevy_ecs::change_detection::NonSendMut<bevy_winit::accessibility::AccessKitAdapters>) does not exist: bevy_ecs::event::Events<bevy_window::event::WindowResized>
stack backtrace:
   0: rust_begin_unwind
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:661:5
   1: core::panicking::panic_fmt
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/panicking.rs:74:14
   2: <bevy_ecs::change_detection::ResMut<T> as bevy_ecs::system::system_param::SystemParam>::get_param::{{closure}}
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/system/system_param.rs:629:17
   3: core::option::Option<T>::unwrap_or_else
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/option.rs:1008:21
   4: <bevy_ecs::change_detection::ResMut<T> as bevy_ecs::system::system_param::SystemParam>::get_param
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/system/system_param.rs:626:21
   5: <(P0,) as bevy_ecs::system::system_param::SystemParam>::get_param
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/system/system_param.rs:1474:20
   6: bevy_ecs::event::_::<impl bevy_ecs::system::system_param::SystemParam for bevy_ecs::event::EventWriter<E>>::get_param
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/event.rs:614:10
   7: <(P0,P1,P2,P3,P4,P5) as bevy_ecs::system::system_param::SystemParam>::get_param
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/system/system_param.rs:1474:20
   8: bevy_ecs::system::function_system::SystemState<Param>::fetch
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/system/function_system.rs:375:22
   9: bevy_ecs::system::function_system::SystemState<Param>::get_unchecked_manual
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/system/function_system.rs:360:18
  10: bevy_ecs::system::function_system::SystemState<Param>::get_mut
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.0/src/system/function_system.rs:240:18
  11: <bevy_winit::state::WinitAppRunnerState<T> as winit::application::ApplicationHandler<T>>::window_event
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.14.0/src/state.rs:195:13
  12: winit::event_loop::dispatch_event_for_app
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/event_loop.rs:631:52
  13: winit::event_loop::EventLoop<T>::run_app::{{closure}}
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/event_loop.rs:265:49
  14: winit::platform_impl::platform::event_loop::map_user_event::{{closure}}
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:163:22
  15: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/alloc/src/boxed.rs:2071:9
  16: winit::platform_impl::platform::event_handler::EventHandler::handle_event
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_handler.rs:125:17
  17: winit::platform_impl::platform::app_state::ApplicationDelegate::handle_event
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app_state.rs:303:9
  18: winit::platform_impl::platform::app_state::ApplicationDelegate::maybe_queue_event
  19: winit::platform_impl::platform::app_state::ApplicationDelegate::maybe_queue_window_event
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app_state.rs:245:9
  20: winit::platform_impl::platform::window_delegate::WindowDelegate::queue_event
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/window_delegate.rs:810:9
  21: winit::platform_impl::platform::window_delegate::WindowDelegate::window_will_close
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/window_delegate.rs:157:13
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <(A,) as objc2::encode::EncodeArguments>::__invoke
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/encode.rs:437:26
  41: objc2::runtime::message_receiver::msg_send_primitive::send_super
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/runtime/message_receiver.rs:193:18
  42: objc2::runtime::message_receiver::MessageReceiver::send_super_message
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/runtime/message_receiver.rs:477:33
  43: objc2::__macro_helpers::msg_send::MsgSend::send_super_message
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/__macro_helpers/msg_send.rs:53:13
  44: objc2::__macro_helpers::msg_send::MsgSend::send_super_message_static
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/__macro_helpers/msg_send.rs:71:18
  45: winit::platform_impl::platform::app::WinitApplication::send_event
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app.rs:42:26
  46: <unknown>
  47: <unknown>
  48: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}::{{closure}}
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:295:26
  49: objc2::rc::autorelease::autoreleasepool
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/rc/autorelease.rs:438:15
  50: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:281:13
  51: winit::platform_impl::platform::event_handler::EventHandler::set
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_handler.rs:98:9
  52: winit::platform_impl::platform::app_state::ApplicationDelegate::set_event_handler
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app_state.rs:172:9
  53: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:280:9
  54: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:267:9
  55: winit::event_loop::EventLoop<T>::run_app
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/event_loop.rs:265:9
  56: bevy_winit::state::winit_runner
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.14.0/src/state.rs:764:23
  57: core::ops::function::FnOnce::call_once{{vtable.shim}}
  58: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/alloc/src/boxed.rs:2064:9
  59: bevy_app::app::App::run
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.14.0/src/app.rs:169:9
  60: cubes::main
             at ./crates/avian3d/examples/cubes.rs:8:5
  61: core::ops::function::FnOnce::call_once
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x1049c0cb4 - std::backtrace_rs::backtrace::libunwind::trace::he73423706aa23920
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:        0x1049c0cb4 - std::backtrace_rs::backtrace::trace_unsynchronized::h006d749d7235504b
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1049c0cb4 - std::sys::backtrace::_print_fmt::h3fd56195ff3cb131
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/sys/backtrace.rs:68:5
   3:        0x1049c0cb4 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0838a12461bf7a75
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/sys/backtrace.rs:44:22
   4:        0x1049dc440 - core::fmt::rt::Argument::fmt::h377ba7521b4a0b50
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/fmt/rt.rs:173:76
   5:        0x1049dc440 - core::fmt::write::h1ca326bdbcc0cdf2
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/fmt/mod.rs:1174:21
   6:        0x1049be4d4 - std::io::Write::write_fmt::h0bc2f3bdb4384a71
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/io/mod.rs:1835:15
   7:        0x1049c0b0c - std::sys::backtrace::_print::hcd7bd674bb3e28ea
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/sys/backtrace.rs:47:5
   8:        0x1049c0b0c - std::sys::backtrace::print::hac1920577da9129b
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/sys/backtrace.rs:34:9
   9:        0x1049c1ce8 - std::panicking::default_hook::{{closure}}::h9031a23295282fc7
  10:        0x1049c19b4 - std::panicking::default_hook::h9fc4e04330353425
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:292:9
  11:        0x1049c2720 - std::panicking::rust_panic_with_hook::h68ac49b9c8aa43c8
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:796:13
  12:        0x1049c2048 - std::panicking::begin_panic_handler::{{closure}}::h2a003216b3832c57
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:663:13
  13:        0x1049c1140 - std::sys::backtrace::__rust_end_short_backtrace::hb9932431605c4ac9
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/sys/backtrace.rs:171:18
  14:        0x1049c1d38 - rust_begin_unwind
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:661:5
  15:        0x104ac46ac - core::panicking::panic_nounwind_fmt::runtime::hfb0ae6d54e7d9f19
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/panicking.rs:112:18
  16:        0x104ac46ac - core::panicking::panic_nounwind_fmt::h94e895afb1132e42
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/panicking.rs:122:5
  17:        0x104ac4724 - core::panicking::panic_nounwind::h9caa9b7c8bbf3056
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/panicking.rs:221:5
  18:        0x104ac489c - core::panicking::panic_cannot_unwind::ha731d111095839b0
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/panicking.rs:309:5
  19:        0x1033065b8 - winit::platform_impl::platform::window_delegate::WindowDelegate::window_will_close::ha462bf870926972c
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/macros/declare_class.rs:981:25
  20:        0x182c26b1c - <unknown>
  21:        0x182cbadb8 - <unknown>
  22:        0x182cbad00 - <unknown>
  23:        0x182bf5648 - <unknown>
  24:        0x183d11464 - <unknown>
  25:        0x186f41d8c - <unknown>
  26:        0x186710838 - <unknown>
  27:        0x186751ca4 - <unknown>
  28:        0x182c5dd4c - <unknown>
  29:        0x1866a3e80 - <unknown>
  30:        0x1866954e4 - <unknown>
  31:        0x18662dc70 - <unknown>
  32:        0x1866f74a4 - <unknown>
  33:        0x186ca4af4 - <unknown>
  34:        0x186b20318 - <unknown>
  35:        0x1866f66bc - <unknown>
  36:        0x186c7b9a4 - <unknown>
  37:        0x186c79ae8 - <unknown>
  38:        0x103322f30 - <(A,) as objc2::encode::EncodeArguments>::__invoke::h63c21fc76180b0cf
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/encode.rs:437:26
  39:        0x103322f30 - objc2::runtime::message_receiver::msg_send_primitive::send_super::h01ffb811fa18178b
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/runtime/message_receiver.rs:193:18
  40:        0x103322f30 - objc2::runtime::message_receiver::MessageReceiver::send_super_message::hfed8db69cbde8255
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/runtime/message_receiver.rs:477:33
  41:        0x103322f30 - objc2::__macro_helpers::msg_send::MsgSend::send_super_message::h641f1f3a3617353f
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/__macro_helpers/msg_send.rs:53:13
  42:        0x103322f30 - objc2::__macro_helpers::msg_send::MsgSend::send_super_message_static::h4c4599ed219d9326
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/__macro_helpers/msg_send.rs:71:18
  43:        0x103322f30 - winit::platform_impl::platform::app::WinitApplication::send_event::h78cdd5c8a3195915
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app.rs:42:26
  44:        0x1868c78cc - <unknown>
  45:        0x18647bcdc - <unknown>
  46:        0x10329bda0 - winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}::{{closure}}::hf53a01ac7095a75b
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:295:26
  47:        0x10329bda0 - objc2::rc::autorelease::autoreleasepool::h0620a295c30b839c
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/rc/autorelease.rs:438:15
  48:        0x10329bda0 - winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}::hac932270d69f07cf
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:281:13
  49:        0x10329bda0 - winit::platform_impl::platform::event_handler::EventHandler::set::hd8c167cd863c6c3d
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_handler.rs:98:9
  50:        0x1032a0a50 - winit::platform_impl::platform::app_state::ApplicationDelegate::set_event_handler::he4796fd383b0a333
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app_state.rs:172:9
  51:        0x1032a0a50 - winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::hec7196913496b745
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:280:9
  52:        0x103285f14 - winit::platform_impl::platform::event_loop::EventLoop<T>::run::h898c797e9625c9c3
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:267:9
  53:        0x103285f14 - winit::event_loop::EventLoop<T>::run_app::hfe765e40bdbc79dc
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/event_loop.rs:265:9
  54:        0x103285f14 - bevy_winit::state::winit_runner::h02d229a0137ebf0d
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.14.0/src/state.rs:764:23
  55:        0x1032a4cb0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h25de29b7994910b8
  56:        0x1047f3e14 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1324794a31394e8c
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/alloc/src/boxed.rs:2064:9
  57:        0x1047f3e14 - bevy_app::app::App::run::hb5dd08f7a8699bf3
                               at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.14.0/src/app.rs:169:9
  58:        0x102f57614 - cubes::main::h223c2b03d5bc96f5
                               at /me/bevy_xpbd/crates/avian3d/examples/cubes.rs:8:5
  59:        0x102f54ca0 - core::ops::function::FnOnce::call_once::h025e4f59101852cc
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/ops/function.rs:250:5
  60:        0x102f54ca0 - std::sys::backtrace::__rust_begin_short_backtrace::h0e06bc6c4aa3db86
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/sys/backtrace.rs:155:18
  61:        0x102f4e4d0 - std::rt::lang_start::{{closure}}::h926ee1b313e69fc7
  62:        0x1049ba37c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd0242712a5ae8bdf
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/ops/function.rs:284:13
  63:        0x1049ba37c - std::panicking::try::do_call::h349da0b335b77a12
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:553:40
  64:        0x1049ba37c - std::panicking::try::hd63afee1c6f2be1b
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:517:19
  65:        0x1049ba37c - std::panic::catch_unwind::h3c7cfd07c7936745
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panic.rs:350:14
  66:        0x1049ba37c - std::rt::lang_start_internal::{{closure}}::h635c64a2011d8cfc
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/rt.rs:141:48
  67:        0x1049ba37c - std::panicking::try::do_call::h3bc82f0b41b239e7
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:553:40
  68:        0x1049ba37c - std::panicking::try::h0f8805615085b3c3
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panicking.rs:517:19
  69:        0x1049ba37c - std::panic::catch_unwind::hf39001e0fc157db7
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/panic.rs:350:14
  70:        0x1049ba37c - std::rt::lang_start_internal::h8006ed5c1a6deca9
                               at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/std/src/rt.rs:141:20
  71:        0x102f5869c - _main
thread caused non-unwinding panic. aborting.
```

Versions:

```
❯ rustc --version
rustc 1.81.0-nightly (524d806c6 2024-07-05)
```

I'm on `main` / d73349f.

If I change the dev-dependencies from this:

```
bevy = { version = "0.14", default-features = false, features = ["bevy_gltf"] }
```

To this:

```
bevy = { version = "0.14" }
```

It does not crash.

**Comment by mgi388** [comment]
Hmm maybe this is something that should be fixed by bevy not avian. Guess it depends if bevy is meant to work OOTB when default-features is false.

**Comment by Jondolf** [comment]
Hmm, I can't reproduce this on Windows. `bevy_winit` should also be enabled because of the `examples_common_3d` crate, and `WindowPlugin` and `WinitPlugin` should be getting added by `DefaultPlugins`, so I don't see why it would crash on those resources not existing 🤔

**Comment by janhohenheim** [comment]
Can confirm I get the same behavior on my macOS, including this nice screen:
<img width="1112" alt="image" src="https://github.com/Jondolf/avian/assets/9047632/b14d49fc-e18f-4775-9a20-61ff49ca7ccd">

@Jondolf I'm not sure how translatable CMD+Q is to ALT+F4 on Windows.

**Comment by JeanMertz** [comment]
While I'm not using Avian, I do get the same error on Bevy 0.14, running on a Mac. I have explicitly specified each bevy crate in my `Cargo.toml` (e.g. I don't use the top-level `bevy` crate), and I always set `default-features = false` to get the minimum number of dependencies I need. I suspect there's a `default` feature somewhere that got added that needs to be added explicitly in this case, but I haven't found the culprit yet.

**Comment by janhohenheim** [comment]
@JeanMertz have you opened an issue on Bevy that we could link to?
